spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://112.220.26.195:3309/imsdbnew
    username: imsapp
    password: im5App!
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
#server:
#  port: 8088

mybatis:
  mapper-locations: classpath:mapper/*.xml
